import type { Config } from "tailwindcss";

// Bu dosyadaki her değer VEYO Education DESIGN.md dosyasından birebir alınmıştır.
// Tasarım sistemini güncellemek için tek kaynak burasıdır.
const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#191c1e",
        primary: "#000000",
        "secondary-fixed": "#e1e0ff",
        "on-primary": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "on-secondary-fixed": "#07006c",
        "on-tertiary-fixed": "#400010",
        "surface-variant": "#e0e3e5",
        "tertiary-fixed-dim": "#ffb2b9",
        "surface-tint": "#565e74",
        "inverse-on-surface": "#eff1f3",
        "secondary-fixed-dim": "#c0c1ff",
        "on-primary-fixed-variant": "#3f465c",
        "outline-variant": "#c6c6cd",
        "tertiary-container": "#400010",
        "secondary-container": "#6063ee",
        "surface-container-lowest": "#ffffff",
        outline: "#76777d",
        "surface-container": "#eceef0",
        "on-tertiary-container": "#da586c",
        secondary: "#4648d4",
        error: "#ba1a1a",
        "inverse-primary": "#bec6e0",
        "surface-bright": "#f7f9fb",
        "on-error-container": "#93000a",
        "on-primary-container": "#7c839b",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#891933",
        surface: "#f7f9fb",
        "tertiary-fixed": "#ffdadc",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "inverse-surface": "#2d3133",
        "on-secondary-container": "#fffbff",
        "primary-container": "#131b2e",
        "on-surface-variant": "#45464d",
        "surface-dim": "#d8dadc",
        "primary-fixed-dim": "#bec6e0",
        "primary-fixed": "#dae2fd",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#2f2ebe",
        background: "#f7f9fb",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#131b2e",
        "on-background": "#191c1e",
        tertiary: "#000000",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        gutter: "24px",
        "unit-xs": "4px",
        "container-max": "1280px",
        "unit-sm": "8px",
        "unit-lg": "24px",
        "unit-xl": "48px",
        "unit-md": "16px",
      },
      fontFamily: {
        sans: ["var(--font-plus-jakarta-sans)"],
      },
      fontSize: {
        "headline-xl-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-2xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-2xl-mobile": ["32px", { lineHeight: "40px", fontWeight: "800" }],
      },
    },
  },
  plugins: [],
};

export default config;
